# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: jb-embed

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      # Windows ARM64 is rare, skip it
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - embed.py

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  header: |
    ## jb-embed {{ .Version }}
    
    Local embedding service powered by [jumpboot](https://github.com/richinsley/jumpboot) and sentence-transformers.
    
    ### First Run
    On first run, jb-embed will bootstrap a Python environment with sentence-transformers.
    This takes a few minutes but only happens once.
    
    ### Quick Start
    ```bash
    # CLI mode
    ./jb-embed "hello world"
    
    # Server mode (for network deployment)
    ./jb-embed serve --port 8420
    ```
  footer: |
    ---
    
    **Full Changelog**: https://github.com/calobozan/jb-embed/compare/v0.1.0...{{ .Tag }}
